<%@ Page Language="c#" Codebehind="EnrolmentToolTip.aspx.cs" AutoEventWireup="false" Inherits="ssCaseConferencing.Flows.FlowLearners.ScrnEnrolmentToolTip" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssCaseConferencing" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="RichWidgets_widgets" TagName="Kq8LrKI8_nU2pGd0T74Vmcw" Src="Blocks\CaseConferencing\LayoutsOther\Layout_Popup.ascx" %>
<%= CaseConferencing_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<RichWidgets_widgets:Kq8LrKI8_nU2pGd0T74Vmcw runat="server" id="RichWidgets_wt_WebBlockInstance1" OnEvaluateParameters="RichWidgets_webBlck_WebBlockInstance1_onDataBinding" InstanceID="_WebBlockInstance1"><phMainContent><osweb:Container runat="server" id="wt_Container12" anonymous="true" onDataBinding="cnt_Container12_onDataBinding"><osweb:IfPlaceHolder runat="server"><osweb:If runat="server" visible="<%# if_wt_If5() %>"><osweb:PlaceHolder runat="server"><%# "No active enrolments...." %></osweb:PlaceHolder></osweb:If><osweb:If runat="server" visible="<%# !if_wt_If5() %>"><osweb:Container runat="server" id="wt_Container7" anonymous="true" onDataBinding="cnt_Container7_onDataBinding"><osweb:PlaceHolder runat="server"><%# OutSystems.HubEdition.RuntimePlatform.RuntimePlatformUtils.ExtendedHtmlEncode(expression_InlineExpression14()) %></osweb:PlaceHolder></osweb:Container><osweb:Iterator runat="server" id="wtListRecords1" onDataBinding="recListListRecords1_onDataBinding" cssClass="ListRecords" OnItemCommand="recListListRecords1_Select" OnSetViewStateStorage="recListListRecords1_Store" OnClearViewStateStorage="recListListRecords1_Clear" OnListRefreshDataBind="recListListRecords1_ListRefreshDataBind"><ItemTemplate><osweb:Container runat="server" id="wt_Container11" anonymous="true" onDataBinding="cnt_Container11_onDataBinding" style="margin-top: 0px"><osweb:Span runat="server" id="wt_InlineExpression4" anonymous="true" class="OfferingName"><%# OutSystems.HubEdition.RuntimePlatform.RuntimePlatformUtils.ExtendedHtmlEncode(expression_InlineExpression4()) %></osweb:Span></osweb:Container><osweb:Container runat="server" id="wt_Container6" anonymous="true" onDataBinding="cnt_Container6_onDataBinding" style="margin-top: 0px"><osweb:Span runat="server" id="wt_InlineExpression10" anonymous="true" class="OfferingDetail"><%# OutSystems.HubEdition.RuntimePlatform.RuntimePlatformUtils.ExtendedHtmlEncode(expression_InlineExpression10()) %></osweb:Span></osweb:Container></ItemTemplate><InvisibleTemplate><%# recListListRecords1_Store(Container.DataItem, Container.ItemIndex) %></InvisibleTemplate></osweb:Iterator></osweb:If></osweb:IfPlaceHolder></osweb:Container></phMainContent></RichWidgets_widgets:Kq8LrKI8_nU2pGd0T74Vmcw><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
