<%@ Page Language="c#" Codebehind="HelpUpdatesUserGuide.aspx.cs" AutoEventWireup="false" Inherits="ssCaseConferencing.Flows.FlowHelpFlow.ScrnHelpUpdatesUserGuide" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssCaseConferencing" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="widgets" TagName="KPb4nFremV0OV78MwfkNYsQ" Src="Blocks\CaseConferencing\HelpFlow\HelpUpdatesLayout.ascx" %><%@ Register TagPrefix="RichWidgets_widgets" TagName="KmbfKJ2gWQUq1Gwk_0SjV4w" Src="Blocks\CaseConferencing\RichWidgets\Icon.ascx" %>
<%= CaseConferencing_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<widgets:KPb4nFremV0OV78MwfkNYsQ runat="server" id="wt_WebBlockInstance10" OnEvaluateParameters="webBlck_WebBlockInstance10_onDataBinding" InstanceID="_WebBlockInstance10"><phTitle><osweb:PlaceHolder runat="server"><%# "Help" %></osweb:PlaceHolder></phTitle><phActions></phActions><phHelpUpdatesContent><osweb:Container runat="server" id="wt_Container16" anonymous="true" onDataBinding="cnt_Container16_onDataBinding" cssClass="UserGuideTitle"><osweb:PlaceHolder runat="server"><%# "User Guide(s)" %></osweb:PlaceHolder></osweb:Container><osweb:Container runat="server" id="wt_Container14" anonymous="true" onDataBinding="cnt_Container14_onDataBinding"><osweb:Iterator runat="server" id="wtListRecords1" onDataBinding="recListListRecords1_onDataBinding" cssClass="ListRecords" OnItemCommand="recListListRecords1_Select" OnSetViewStateStorage="recListListRecords1_Store" OnClearViewStateStorage="recListListRecords1_Clear" OnListRefreshDataBind="recListListRecords1_ListRefreshDataBind" NeedsBreakAfter="true"><ItemTemplate><osweb:Container runat="server" id="wt_Container18" anonymous="true" onDataBinding="cnt_Container18_onDataBinding" cssClass="UpdateContainer"><osweb:Container runat="server" id="wt_Container17" anonymous="true" onDataBinding="cnt_Container17_onDataBinding" cssClass="UpdateTitle"><osweb:PlaceHolder runat="server"><%# OutSystems.HubEdition.RuntimePlatform.RuntimePlatformUtils.ExtendedHtmlEncode(expression_InlineExpression21()) %></osweb:PlaceHolder></osweb:Container><osweb:Container runat="server" id="wt_Container15" anonymous="true" onDataBinding="cnt_Container15_onDataBinding" cssClass="UpdateHTML"><osweb:PlaceHolder runat="server"><%# expression_InlineExpression7() %></osweb:PlaceHolder></osweb:Container><osweb:Container runat="server" id="wt_Container1" anonymous="true" onDataBinding="cnt_Container1_onDataBinding" cssClass="UpdateDownloadLink"><osweb:IfPlaceHolder runat="server"><osweb:If runat="server" visible="<%# if_wt_If9() %>"><osweb:LinkButton runat="server" id="wt_Link12" Visible="<%# lnk_Link12_isVisible() %>" Enabled="<%# lnk_Link12_isEnabled() %>" CausesValidation="false"><RichWidgets_widgets:KmbfKJ2gWQUq1Gwk_0SjV4w runat="server" id="RichWidgets_wt_WebBlockInstance11" OnEvaluateParameters="RichWidgets_webBlck_WebBlockInstance11_onDataBinding" InstanceID="_WebBlockInstance11"></RichWidgets_widgets:KmbfKJ2gWQUq1Gwk_0SjV4w><osweb:PlaceHolder runat="server"><%# "Download Attached File" %></osweb:PlaceHolder></osweb:LinkButton></osweb:If><osweb:If runat="server" visible="<%# !if_wt_If9() %>"></osweb:If></osweb:IfPlaceHolder></osweb:Container></osweb:Container></ItemTemplate><InvisibleTemplate><%# recListListRecords1_Store(Container.DataItem, Container.ItemIndex) %></InvisibleTemplate></osweb:Iterator></osweb:Container></phHelpUpdatesContent></widgets:KPb4nFremV0OV78MwfkNYsQ><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
