<%@ Page Language="c#" Codebehind="LearnerDetailsTabs.aspx.cs" AutoEventWireup="false" Inherits="ssCaseConferencing.Flows.FlowLearnerView.ScrnLearnerDetailsTabs" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssCaseConferencing" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="widgets" TagName="KY8fQXOFtqEiDzEzWU_VcSw" Src="Blocks\CaseConferencing\LearnerView\LearnerDetailsLayout.ascx" %><%@ Register TagPrefix="widgets" TagName="K0sfuKre6TUqxnEDun5a7Dw" Src="Blocks\CaseConferencing\Learner_ILP\ILP_Tab.ascx" %><%@ Register TagPrefix="widgets" TagName="KtCluxfvnUEimrSYLYCBGxg" Src="Blocks\CaseConferencing\Learner_InitialAssessment\SIAS_Tab.ascx" %><%@ Register TagPrefix="widgets" TagName="KWDkkgrr900uymjDZ716diQ" Src="Blocks\CaseConferencing\Learner_Programme\Programme_Tab.ascx" %><%@ Register TagPrefix="widgets" TagName="KkTnvZt_YJUO6ntlvJHbw4A" Src="Blocks\CaseConferencing\Safeguarding\Safeguarding_Tab.ascx" %><%@ Register TagPrefix="widgets" TagName="KimlcMmlI_EOWzvUicUzKCQ" Src="Blocks\CaseConferencing\Learner_ProgressReport\ProgressReport_Tab.ascx" %>
<%= CaseConferencing_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<widgets:KY8fQXOFtqEiDzEzWU_VcSw runat="server" id="wt_WebBlockInstance6" OnEvaluateParameters="webBlck_WebBlockInstance6_onDataBinding" InstanceID="_WebBlockInstance6"><phRAG></phRAG><phILP><widgets:K0sfuKre6TUqxnEDun5a7Dw runat="server" id="wt_WebBlockInstance4" OnEvaluateParameters="webBlck_WebBlockInstance4_onDataBinding" InstanceID="_WebBlockInstance4"></widgets:K0sfuKre6TUqxnEDun5a7Dw></phILP><phSIAS><widgets:KtCluxfvnUEimrSYLYCBGxg runat="server" id="wt_WebBlockInstance12" OnEvaluateParameters="webBlck_WebBlockInstance12_onDataBinding" InstanceID="_WebBlockInstance12"></widgets:KtCluxfvnUEimrSYLYCBGxg></phSIAS><phProgramme><widgets:KWDkkgrr900uymjDZ716diQ runat="server" id="wt_WebBlockInstance9" OnEvaluateParameters="webBlck_WebBlockInstance9_onDataBinding" InstanceID="_WebBlockInstance9"></widgets:KWDkkgrr900uymjDZ716diQ></phProgramme><phSafeguarding><widgets:KkTnvZt_YJUO6ntlvJHbw4A runat="server" id="wt_WebBlockInstance5" OnEvaluateParameters="webBlck_WebBlockInstance5_onDataBinding" InstanceID="_WebBlockInstance5" IncludeSpan="true"></widgets:KkTnvZt_YJUO6ntlvJHbw4A></phSafeguarding><phProgressReport><osweb:Container runat="server" id="wt_Container3" anonymous="true" onDataBinding="cnt_Container3_onDataBinding"><widgets:KimlcMmlI_EOWzvUicUzKCQ runat="server" id="wt_WebBlockInstance8" OnEvaluateParameters="webBlck_WebBlockInstance8_onDataBinding" InstanceID="_WebBlockInstance8"></widgets:KimlcMmlI_EOWzvUicUzKCQ></osweb:Container></phProgressReport></widgets:KY8fQXOFtqEiDzEzWU_VcSw><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
