<%@ Page Language="c#" Codebehind="LearnerDetailCategory.aspx.cs" AutoEventWireup="false" Inherits="ssCaseConferencing.Flows.FlowLearnerView.ScrnLearnerDetailCategory" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssCaseConferencing" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="widgets" TagName="KY8fQXOFtqEiDzEzWU_VcSw" Src="Blocks\CaseConferencing\LearnerView\LearnerDetailsLayout.ascx" %><%@ Register TagPrefix="widgets" TagName="KAqCgWaV9z0CqW1ZN1otFQA" Src="Blocks\CaseConferencing\StaffView\LearnerDetailCategory_Edit.ascx" %><%@ Register TagPrefix="widgets" TagName="KVyPDvhUlgUuFcBT9_lJCSA" Src="Blocks\CaseConferencing\LearnerView\Competencies_List.ascx" %><%@ Register TagPrefix="widgets" TagName="Kl_A0KL0PaUa3RBAfrU_xSw" Src="Blocks\CaseConferencing\Learner_ILP\Targets_List.ascx" %>
<%= CaseConferencing_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<osweb:Container runat="server" id="wt_Container20" anonymous="true" onDataBinding="cnt_Container20_onDataBinding"><widgets:KY8fQXOFtqEiDzEzWU_VcSw runat="server" id="wtDetailsLayout" OnEvaluateParameters="webBlckDetailsLayout_onDataBinding" InstanceID="DetailsLayout" IncludeSpan="true"><phRAG><widgets:KAqCgWaV9z0CqW1ZN1otFQA runat="server" id="wtStaffViewWB" OnEvaluateParameters="webBlckStaffViewWB_onDataBinding" InstanceID="StaffViewWB" IncludeSpan="true"></widgets:KAqCgWaV9z0CqW1ZN1otFQA><osweb:IfPlaceHolder runat="server"><osweb:If runat="server" visible="<%# if_wt_If7() %>"><widgets:KVyPDvhUlgUuFcBT9_lJCSA runat="server" id="wt_WebBlockInstance6" onAjaxNotify="webBlck_WebBlockInstance6_AjaxNotify" OnEvaluateParameters="webBlck_WebBlockInstance6_onDataBinding" InstanceID="_WebBlockInstance6"></widgets:KVyPDvhUlgUuFcBT9_lJCSA></osweb:If><osweb:If runat="server" visible="<%# !if_wt_If7() %>"></osweb:If></osweb:IfPlaceHolder><osweb:Container runat="server" id="wt_Container19" anonymous="true" onDataBinding="cnt_Container19_onDataBinding"><osweb:Container runat="server" id="wtTargets" onDataBinding="cntTargets_onDataBinding"><osweb:Iterator runat="server" id="wtListRecords1" onDataBinding="recListListRecords1_onDataBinding" cssClass="ListRecords" OnItemCommand="recListListRecords1_Select" OnSetViewStateStorage="recListListRecords1_Store" OnClearViewStateStorage="recListListRecords1_Clear" OnListRefreshDataBind="recListListRecords1_ListRefreshDataBind"><ItemTemplate><osweb:Container runat="server" id="wtWrapperList" onDataBinding="cntWrapperList_onDataBinding"><osweb:Container runat="server" id="wt_Container14" anonymous="true" onDataBinding="cnt_Container14_onDataBinding"><osweb:Container runat="server" id="wtCategoryLine" onDataBinding="cntCategoryLine_onDataBinding"><widgets:Kl_A0KL0PaUa3RBAfrU_xSw runat="server" id="wt_WebBlockInstance4" onAjaxNotify="webBlck_WebBlockInstance4_AjaxNotify" OnEvaluateParameters="webBlck_WebBlockInstance4_onDataBinding" InstanceID="_WebBlockInstance4"></widgets:Kl_A0KL0PaUa3RBAfrU_xSw></osweb:Container></osweb:Container></osweb:Container></ItemTemplate><InvisibleTemplate><%# recListListRecords1_Store(Container.DataItem, Container.ItemIndex) %></InvisibleTemplate></osweb:Iterator></osweb:Container></osweb:Container></phRAG><phILP></phILP><phSIAS></phSIAS><phProgramme></phProgramme><phSafeguarding></phSafeguarding><phProgressReport></phProgressReport></widgets:KY8fQXOFtqEiDzEzWU_VcSw></osweb:Container><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
