<%@ Page Language="c#" Codebehind="LearnerDetailsPENPortrait.aspx.cs" AutoEventWireup="false" Inherits="ssCaseConferencing.Flows.FlowLearnerView.ScrnLearnerDetailsPENPortrait" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssCaseConferencing" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="widgets" TagName="KY8fQXOFtqEiDzEzWU_VcSw" Src="Blocks\CaseConferencing\LearnerView\LearnerDetailsLayout.ascx" %><%@ Register TagPrefix="RichWidgets_widgets" TagName="Kbbzz9S_an_V_uoCTOfsBiA" Src="Blocks\CaseConferencing\RichWidgets\Popup_Editor.ascx" %>
<%= CaseConferencing_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<widgets:KY8fQXOFtqEiDzEzWU_VcSw runat="server" id="wt_WebBlockInstance15" OnEvaluateParameters="webBlck_WebBlockInstance15_onDataBinding" InstanceID="_WebBlockInstance15"><phRAG><osweb:Container runat="server" id="wtPENPortraitWrapper" onDataBinding="cntPENPortraitWrapper_onDataBinding" cssClass="ContentDetailWrapper"><osweb:Container runat="server" id="wt_Container18" anonymous="true" onDataBinding="cnt_Container18_onDataBinding" cssClass="TitleReward"><osweb:Container runat="server" id="wt_Container2" anonymous="true" onDataBinding="cnt_Container2_onDataBinding" GridCssClasses="OSInline" style="width: 50%"><osweb:PlaceHolder runat="server"><%# "PEN Portrait" %></osweb:PlaceHolder></osweb:Container><osweb:Container runat="server" id="wt_Container12" anonymous="true" onDataBinding="cnt_Container12_onDataBinding" GridCssClasses="OSInline" style="width: 50%; margin-left: 0px" align="right"><osweb:Container runat="server" id="wt_Container5" anonymous="true" onDataBinding="cnt_Container5_onDataBinding" cssClass="HeaderButton" GridCssClasses="OSInline" style="width: 50px"><osweb:HyperLink runat="server" id="wtpopup_penportraitlink" Visible="<%# lnkpopup_penportraitlink_isVisible() %>" Enabled="<%# lnkpopup_penportraitlink_isEnabled() %>" NavigateUrl="<%# lnkpopup_penportraitlink_NavigateUrl() %>"><osweb:PlaceHolder runat="server"><%# OutSystems.HubEdition.RuntimePlatform.RuntimePlatformUtils.ExtendedHtmlEncode(expression_InlineExpression14()) %></osweb:PlaceHolder></osweb:HyperLink></osweb:Container><RichWidgets_widgets:Kbbzz9S_an_V_uoCTOfsBiA runat="server" id="RichWidgets_wt_WebBlockInstance20" onAjaxNotify="RichWidgets_webBlck_WebBlockInstance20_AjaxNotify" OnEvaluateParameters="RichWidgets_webBlck_WebBlockInstance20_onDataBinding" InstanceID="_WebBlockInstance20"></RichWidgets_widgets:Kbbzz9S_an_V_uoCTOfsBiA></osweb:Container></osweb:Container><osweb:Container runat="server" id="wt_Container11" anonymous="true" onDataBinding="cnt_Container11_onDataBinding" GridCssClasses="OSAutoMarginTop"><osweb:PlaceHolder runat="server"><%# OutSystems.HubEdition.RuntimePlatform.RuntimePlatformUtils.ExtendedHtmlEncode(expression_InlineExpression8()) %></osweb:PlaceHolder></osweb:Container><osweb:Container runat="server" id="wtPENPortraitContainer" onDataBinding="cntPENPortraitContainer_onDataBinding"><osweb:Container runat="server" id="wtlastUpdatedContainer" onDataBinding="cntlastUpdatedContainer_onDataBinding" align="right"><osweb:Span runat="server" id="wt_InlineExpression6" anonymous="true" class="Text_Note"><%# OutSystems.HubEdition.RuntimePlatform.RuntimePlatformUtils.ExtendedHtmlEncode(expression_InlineExpression6()) %></osweb:Span></osweb:Container></osweb:Container></osweb:Container></phRAG><phILP></phILP><phSIAS></phSIAS><phProgramme></phProgramme><phSafeguarding></phSafeguarding><phProgressReport></phProgressReport></widgets:KY8fQXOFtqEiDzEzWU_VcSw><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
