<%@ Page Language="c#" Codebehind="LearnerDetailsAttendance.aspx.cs" AutoEventWireup="false" Inherits="ssCaseConferencing.Flows.FlowLearnerView.ScrnLearnerDetailsAttendance" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssCaseConferencing" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="widgets" TagName="KY8fQXOFtqEiDzEzWU_VcSw" Src="Blocks\CaseConferencing\LearnerView\LearnerDetailsLayout.ascx" %><%@ Register TagPrefix="widgets" TagName="Kbgme051IW0O0EWMJ_ZKAKQ" Src="Blocks\CaseConferencing\StaffView\StudentAttendanceSummaryBlock.ascx" %>
<%= CaseConferencing_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<widgets:KY8fQXOFtqEiDzEzWU_VcSw runat="server" id="wt_WebBlockInstance14" OnEvaluateParameters="webBlck_WebBlockInstance14_onDataBinding" InstanceID="_WebBlockInstance14"><phRAG><osweb:Container runat="server" id="wt_Container4" anonymous="true" onDataBinding="cnt_Container4_onDataBinding"><osweb:Container runat="server" id="wtActiveEnrolments" onDataBinding="cntActiveEnrolments_onDataBinding"><widgets:Kbgme051IW0O0EWMJ_ZKAKQ runat="server" id="wt_WebBlockInstance9" OnEvaluateParameters="webBlck_WebBlockInstance9_onDataBinding" InstanceID="_WebBlockInstance9"></widgets:Kbgme051IW0O0EWMJ_ZKAKQ></osweb:Container><osweb:Container runat="server" id="wtCompletedEnrolments" onDataBinding="cntCompletedEnrolments_onDataBinding"><widgets:Kbgme051IW0O0EWMJ_ZKAKQ runat="server" id="wt_WebBlockInstance2" OnEvaluateParameters="webBlck_WebBlockInstance2_onDataBinding" InstanceID="_WebBlockInstance2"></widgets:Kbgme051IW0O0EWMJ_ZKAKQ></osweb:Container><osweb:Container runat="server" id="wtWithdrawnEnrolments" onDataBinding="cntWithdrawnEnrolments_onDataBinding"><widgets:Kbgme051IW0O0EWMJ_ZKAKQ runat="server" id="wt_WebBlockInstance10" OnEvaluateParameters="webBlck_WebBlockInstance10_onDataBinding" InstanceID="_WebBlockInstance10"></widgets:Kbgme051IW0O0EWMJ_ZKAKQ></osweb:Container><osweb:Container runat="server" id="wtTransferredEnrolments" onDataBinding="cntTransferredEnrolments_onDataBinding"><widgets:Kbgme051IW0O0EWMJ_ZKAKQ runat="server" id="wt_WebBlockInstance13" OnEvaluateParameters="webBlck_WebBlockInstance13_onDataBinding" InstanceID="_WebBlockInstance13"></widgets:Kbgme051IW0O0EWMJ_ZKAKQ></osweb:Container></osweb:Container></phRAG><phILP></phILP><phSIAS></phSIAS><phProgramme></phProgramme><phSafeguarding></phSafeguarding><phProgressReport></phProgressReport></widgets:KY8fQXOFtqEiDzEzWU_VcSw><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
