<%@ Page Language="c#" Codebehind="Popup_Notes.aspx.cs" AutoEventWireup="false" Inherits="ssCaseConferencing.Flows.FlowCourses.ScrnPopup_Notes" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssCaseConferencing" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="widgets" TagName="KHtW7GNYBskijYiZHuvzUvw" Src="Blocks\CaseConferencing\Common\Popup_Editor_Layout.ascx" %><%@ Register TagPrefix="RichWidgets_widgets" TagName="KmbfKJ2gWQUq1Gwk_0SjV4w" Src="Blocks\CaseConferencing\RichWidgets\Icon.ascx" %>
<%= CaseConferencing_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<widgets:KHtW7GNYBskijYiZHuvzUvw runat="server" id="wt_WebBlockInstance11" OnEvaluateParameters="webBlck_WebBlockInstance11_onDataBinding" InstanceID="_WebBlockInstance11"><phTitle><RichWidgets_widgets:KmbfKJ2gWQUq1Gwk_0SjV4w runat="server" id="RichWidgets_wt_WebBlockInstance3" OnEvaluateParameters="RichWidgets_webBlck_WebBlockInstance3_onDataBinding" InstanceID="_WebBlockInstance3"></RichWidgets_widgets:KmbfKJ2gWQUq1Gwk_0SjV4w><osweb:PlaceHolder runat="server"><%# " Notes" %></osweb:PlaceHolder></phTitle><phContent><osweb:Container runat="server" id="wt_Container2" anonymous="true" onDataBinding="cnt_Container2_onDataBinding" GridCssClasses="ThemeGrid_Width5"><osweb:Container runat="server" id="wt_Container6" anonymous="true" onDataBinding="cnt_Container6_onDataBinding"><osweb:TextBox runat="server" id="wt_Input4" onDataBinding="inputwt_Input4_onDataBinding" GridCssClasses="OSFillParent" Visible="<%# inputwt_Input4_isVisible() %>" ReadOnly="<%# !inputwt_Input4_isEnabled() %>" OnDefaultMandatoryValidationMessage="GetMandatoryValidatorMsg" OnDefaultTypeValidationMessage="GetTextValidatorMsg" textmode="MultiLine" rows="6" text="<%# inputwt_Input4_input_value() %>" onTextChanged="inputwt_Input4_input_onTextChanged" Mandatory="<%# inputwt_Input4_isMandatory() %>"/><osweb:RequiredFieldTextValidator  runat="server" display="Dynamic" id="wt_Input4ValidatorRequired" ErrorMessage="<%# CaseConferencing_Properties.MandatoryValidatorMsg %>" ControlToValidate="wt_Input4"/><osweb:TextValidator runat="server" display="Dynamic" id="wt_Input4ValidatorType" ErrorMessage="<%# CaseConferencing_Properties.TextValidatorMsg %>" ControlToValidate="wt_Input4" ClientValidationFunction="OsCustomValidatorText"/></osweb:Container><osweb:Container runat="server" id="wt_Container7" anonymous="true" onDataBinding="cnt_Container7_onDataBinding" style="margin-top: 10px" align="right"><osweb:Button runat="server" id="wt_Button9" cssClass="Button Is_Default" Visible="<%# btn_Button9_isVisible() %>" Enabled="<%# btn_Button9_isEnabled() %>" CausesValidation="false" text="<%# btn_Button9_getLabel() %>"/><osweb:Button runat="server" id="wt_Button5" cssClass="Button" GridCssClasses="ThemeGrid_MarginGutter" Visible="<%# btn_Button5_isVisible() %>" Enabled="<%# btn_Button5_isEnabled() %>" CausesValidation="false" text="<%# btn_Button5_getLabel() %>"/></osweb:Container></osweb:Container></phContent></widgets:KHtW7GNYBskijYiZHuvzUvw><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
