<%@ Page Language="c#" Codebehind="Popup_ExtraCA.aspx.cs" AutoEventWireup="false" Inherits="ssCaseConferencing.Flows.FlowLearnerView.ScrnPopup_ExtraCA" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssCaseConferencing" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="widgets" TagName="KHtW7GNYBskijYiZHuvzUvw" Src="Blocks\CaseConferencing\Common\Popup_Editor_Layout.ascx" %>
<%= CaseConferencing_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<widgets:KHtW7GNYBskijYiZHuvzUvw runat="server" id="wt_WebBlockInstance12" OnEvaluateParameters="webBlck_WebBlockInstance12_onDataBinding" InstanceID="_WebBlockInstance12"><phTitle><osweb:PlaceHolder runat="server"><%# "Student - Extra Curricular Activities" %></osweb:PlaceHolder></phTitle><phContent><osweb:Container runat="server" id="wt_Container9" anonymous="true" onDataBinding="cnt_Container9_onDataBinding"><osweb:PlaceHolder runat="server"><%# "Student Involved with Cornwall College Students Union " %></osweb:PlaceHolder><osweb:CheckBox runat="server" id="wt_CheckBox3" GridCssClasses="ThemeGrid_MarginGutter" Visible="<%# chk_CheckBox3_isVisible() %>" Enabled="<%# chk_CheckBox3_isEnabled() %>" Checked="<%# chk_CheckBox3_checked_value() %>" onCheckedChanged="chk_CheckBox3_checkbox_onCheckedChanged"/></osweb:Container><osweb:Container runat="server" id="wt_Container14" anonymous="true" onDataBinding="cnt_Container14_onDataBinding" GridCssClasses="OSAutoMarginTop"><osweb:PlaceHolder runat="server"><%# "Any Additional Extra Curricular Activities  : " %></osweb:PlaceHolder></osweb:Container><osweb:Container runat="server" id="wt_Container2" anonymous="true" onDataBinding="cnt_Container2_onDataBinding" GridCssClasses="OSAutoMarginTop"><osweb:TextBox runat="server" id="wt_Input8" style="width: 610px" Visible="<%# inputwt_Input8_isVisible() %>" ReadOnly="<%# !inputwt_Input8_isEnabled() %>" maxlength="4000" onchange="OsLimitInput(this,event,4000);" onkeyup="OsLimitInput(this,event,4000);" OnDefaultMandatoryValidationMessage="GetMandatoryValidatorMsg" OnDefaultTypeValidationMessage="GetTextValidatorMsg" textmode="MultiLine" rows="6" text="<%# inputwt_Input8_input_value() %>" onTextChanged="inputwt_Input8_input_onTextChanged" Mandatory="<%# inputwt_Input8_isMandatory() %>"/><osweb:RequiredFieldTextValidator  runat="server" display="Dynamic" id="wt_Input8ValidatorRequired" ErrorMessage="<%# CaseConferencing_Properties.MandatoryValidatorMsg %>" ControlToValidate="wt_Input8"/><osweb:TextValidator runat="server" display="Dynamic" id="wt_Input8ValidatorType" ErrorMessage="<%# CaseConferencing_Properties.TextValidatorMsg %>" ControlToValidate="wt_Input8" ClientValidationFunction="OsCustomValidatorText"/></osweb:Container><osweb:Container runat="server" id="wt_Container10" anonymous="true" onDataBinding="cnt_Container10_onDataBinding" GridCssClasses="OSAutoMarginTop" align="right"><osweb:Container runat="server" id="wt_Container5" anonymous="true" onDataBinding="cnt_Container5_onDataBinding" onAjaxClick="cnt_Container5_AjaxClick" cssClass="HeaderButton" GridCssClasses="OSInline" style="width: 100px"><osweb:PlaceHolder runat="server"><%# "Save" %></osweb:PlaceHolder></osweb:Container></osweb:Container></phContent></widgets:KHtW7GNYBskijYiZHuvzUvw><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
