<%@ Page Language="c#" Codebehind="Popup_LogoSelection.aspx.cs" AutoEventWireup="false" Inherits="ssCaseConferencing.Flows.FlowLearner_ProgressReport.ScrnPopup_LogoSelection" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssCaseConferencing" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="widgets" TagName="KHtW7GNYBskijYiZHuvzUvw" Src="Blocks\CaseConferencing\Common\Popup_Editor_Layout.ascx" %>
<%= CaseConferencing_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<widgets:KHtW7GNYBskijYiZHuvzUvw runat="server" id="wt_WebBlockInstance3" OnEvaluateParameters="webBlck_WebBlockInstance3_onDataBinding" InstanceID="_WebBlockInstance3"><phTitle><osweb:PlaceHolder runat="server"><%# "Select Logo to Appear in Progress Report" %></osweb:PlaceHolder></phTitle><phContent><osweb:Container runat="server" id="wt_Container9" anonymous="true" onDataBinding="cnt_Container9_onDataBinding"><osweb:Iterator runat="server" id="wtListRecords1" onDataBinding="recListListRecords1_onDataBinding" cssClass="ListRecords" OnItemCommand="recListListRecords1_Select" OnSetViewStateStorage="recListListRecords1_Store" OnClearViewStateStorage="recListListRecords1_Clear" OnListRefreshDataBind="recListListRecords1_ListRefreshDataBind"><ItemTemplate><osweb:Container runat="server" id="wt_Container12" anonymous="true" onDataBinding="cnt_Container12_onDataBinding" onAjaxClick="cnt_Container12_AjaxClick" GridCssClasses="OSInline" style="width: 220px; margin-left: 10px; margin-top: 10px" align="center"><osweb:Container runat="server" id="wt_Container15" anonymous="true" onDataBinding="cnt_Container15_onDataBinding" cssClass="CCCardPopup"><osweb:Container runat="server" id="wt_Container2" anonymous="true" onDataBinding="cnt_Container2_onDataBinding"><osweb:Container runat="server" id="wt_Container8" anonymous="true" onDataBinding="cnt_Container8_onDataBinding" cssClass="CardTitlePopup"><osweb:PlaceHolder runat="server"><%# OutSystems.HubEdition.RuntimePlatform.RuntimePlatformUtils.ExtendedHtmlEncode(expression_InlineExpression10()) %></osweb:PlaceHolder></osweb:Container><osweb:Container runat="server" id="wt_Container13" anonymous="true" onDataBinding="cnt_Container13_onDataBinding" cssClass="CardWhitePopup" style="margin-top: 10px"><osweb:Container runat="server" id="wt_Container5" anonymous="true" onDataBinding="cnt_Container5_onDataBinding" align="center"><osweb:DynamicImage runat="server" id="wt_Image11" anonymous="true" Source="<%# img_Image11_getURL() %>" ImageType="External" Width="<%# System.Web.UI.WebControls.Unit.Parse(img_Image11_actualWidth(), System.Globalization.CultureInfo.InvariantCulture) %>" alt=""/></osweb:Container></osweb:Container></osweb:Container></osweb:Container></osweb:Container></ItemTemplate><InvisibleTemplate><%# recListListRecords1_Store(Container.DataItem, Container.ItemIndex) %></InvisibleTemplate></osweb:Iterator></osweb:Container><osweb:Container runat="server" id="wt_Container6" anonymous="true" onDataBinding="cnt_Container6_onDataBinding" GridCssClasses="OSAutoMarginTop"><osweb:Button runat="server" id="wt_Button1" cssClass="Button Is_Default" Visible="<%# btn_Button1_isVisible() %>" Enabled="<%# btn_Button1_isEnabled() %>" CausesValidation="false" text="<%# btn_Button1_getLabel() %>"/></osweb:Container></phContent></widgets:KHtW7GNYBskijYiZHuvzUvw><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
