<%@ Page Language="c#" Codebehind="Reports_Main.aspx.cs" AutoEventWireup="false" Inherits="ssCaseConferencing.Flows.FlowReporting.ScrnReports_Main" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssCaseConferencing" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="ThemeProvider_widgets" TagName="Ky1nG5kdyhEesTpKvn40S7g" Src="Blocks\CaseConferencing\MainLayouts\Layout_Main.ascx" %><%@ Register TagPrefix="ThemeProvider_widgets" TagName="KgWHRAp6ig0iU4JPYFzrEhg" Src="Blocks\CaseConferencing\MainLayouts\Menu_Backoffice.ascx" %><%@ Register TagPrefix="ThemeProvider_widgets" TagName="Ku_HwnPUook2ewuMpNl0gyQ" Src="Blocks\CaseConferencing\Common2\TabsClient.ascx" %><%@ Register TagPrefix="RichWidgets_widgets" TagName="KmbfKJ2gWQUq1Gwk_0SjV4w" Src="Blocks\CaseConferencing\RichWidgets\Icon.ascx" %><%@ Register TagPrefix="widgets" TagName="Kg7tM0LMER0qLhWf3tHRLTQ" Src="Blocks\CaseConferencing\Reporting\RAGNotUpdatedIn30.ascx" %><%@ Register TagPrefix="widgets" TagName="K1g7EgbW43UqA1oRQeY9MKA" Src="Blocks\CaseConferencing\Reporting\SafeguardingIssues.ascx" %>
<%= CaseConferencing_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<ThemeProvider_widgets:Ky1nG5kdyhEesTpKvn40S7g runat="server" id="ThemeProvider_wt_WebBlockInstance16" OnEvaluateParameters="ThemeProvider_webBlck_WebBlockInstance16_onDataBinding" InstanceID="_WebBlockInstance16"><phHelpUpdate></phHelpUpdate><phHeaderActions><ThemeProvider_widgets:KgWHRAp6ig0iU4JPYFzrEhg runat="server" id="ThemeProvider_wt_WebBlockInstance15" OnEvaluateParameters="ThemeProvider_webBlck_WebBlockInstance15_onDataBinding" InstanceID="_WebBlockInstance15"></ThemeProvider_widgets:KgWHRAp6ig0iU4JPYFzrEhg></phHeaderActions><phTitle><osweb:PlaceHolder runat="server"><%# "Reporting / Stats" %></osweb:PlaceHolder></phTitle><phActions></phActions><phMainContent><ThemeProvider_widgets:Ku_HwnPUook2ewuMpNl0gyQ runat="server" id="ThemeProvider_wt_WebBlockInstance1" OnEvaluateParameters="ThemeProvider_webBlck_WebBlockInstance1_onDataBinding" InstanceID="_WebBlockInstance1"><phTab1><RichWidgets_widgets:KmbfKJ2gWQUq1Gwk_0SjV4w runat="server" id="RichWidgets_wt_WebBlockInstance26" OnEvaluateParameters="RichWidgets_webBlck_WebBlockInstance26_onDataBinding" InstanceID="_WebBlockInstance26"></RichWidgets_widgets:KmbfKJ2gWQUq1Gwk_0SjV4w><osweb:PlaceHolder runat="server"><%# "RAG " %></osweb:PlaceHolder></phTab1><phTab2><RichWidgets_widgets:KmbfKJ2gWQUq1Gwk_0SjV4w runat="server" id="RichWidgets_wt_WebBlockInstance19" OnEvaluateParameters="RichWidgets_webBlck_WebBlockInstance19_onDataBinding" InstanceID="_WebBlockInstance19"></RichWidgets_widgets:KmbfKJ2gWQUq1Gwk_0SjV4w><osweb:PlaceHolder runat="server"><%# "Safeguarding" %></osweb:PlaceHolder></phTab2><phTab3></phTab3><phTab4></phTab4><phTab5></phTab5><phTab6></phTab6><phContent1><widgets:Kg7tM0LMER0qLhWf3tHRLTQ runat="server" id="wt_WebBlockInstance5" OnEvaluateParameters="webBlck_WebBlockInstance5_onDataBinding" InstanceID="_WebBlockInstance5"></widgets:Kg7tM0LMER0qLhWf3tHRLTQ></phContent1><phContent2><widgets:K1g7EgbW43UqA1oRQeY9MKA runat="server" id="wt_WebBlockInstance21" OnEvaluateParameters="webBlck_WebBlockInstance21_onDataBinding" InstanceID="_WebBlockInstance21" IncludeSpan="true"></widgets:K1g7EgbW43UqA1oRQeY9MKA></phContent2><phContent3></phContent3><phContent4></phContent4><phContent5></phContent5><phContent6></phContent6></ThemeProvider_widgets:Ku_HwnPUook2ewuMpNl0gyQ></phMainContent></ThemeProvider_widgets:Ky1nG5kdyhEesTpKvn40S7g><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
