/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Sms;
using OutSystems.HubEdition.RuntimePlatform.Log;
using OutSystems.HubEdition.RuntimePlatform.Db;
using OutSystems.Internal.Db;
using OutSystems.HubEdition.RuntimePlatform.Email;
using OutSystems.HubEdition.RuntimePlatform.Web;
using OutSystems.RuntimeCommon;
using OutSystems.ObjectKeys;
using System.Resources;

namespace ssCaseConferencing {

	public partial class Actions {
		public class lcvConvertStatusToMark: VarsBag {
			public string inParamStatus;
			public lcvConvertStatusToMark(string inParamStatus) {
				this.inParamStatus = inParamStatus;
			}
		}
		public class lcoConvertStatusToMark: VarsBag {
			public string outParamMark = "";

			public lcoConvertStatusToMark() {
			}
		}
		/// <summary>
		/// Action <code>ActionConvertStatusToMark</code> that represents the Service Studio user action
		///  <code>ConvertStatusToMark</code> <p> Description: </p>
		/// </summary>
		public static void ActionConvertStatusToMark(HeContext heContext, string inParamStatus, out string outParamMark) {
			lcoConvertStatusToMark result = new lcoConvertStatusToMark();
			lcvConvertStatusToMark localVars = new lcvConvertStatusToMark(inParamStatus);
			try {
				if ((((localVars.inParamStatus== "/") || (localVars.inParamStatus== "I")) || (localVars.inParamStatus== "E"))) {
					result.outParamMark = "/"; // Mark = "/"

				} else {
					if ((localVars.inParamStatus== "O")) {
						result.outParamMark = "O"; // Mark = "O"

					} else {
						if ((localVars.inParamStatus== "L")) {
							result.outParamMark = "L"; // Mark = "L"

						} else {
							if (((localVars.inParamStatus== "No Session") || (localVars.inParamStatus== "No Mark"))) {
								result.outParamMark = "-"; // Mark = "-"

							} else {
								if ((localVars.inParamStatus== "N")) {
									result.outParamMark = "N"; // Mark = "N"

								} else {
									if ((localVars.inParamStatus== "A")) {
										result.outParamMark = "A"; // Mark = "A"

									} else {
										result.outParamMark = ""; // Mark = ""

									}

								}

							}

						}

					}

				}
			} // try

			finally {
				outParamMark = result.outParamMark;
			}
		}

		public static class FuncActionConvertStatusToMark {


		}


	}


}