/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Data;
using System.Runtime.Serialization;
using System.Reflection;
using System.Xml;
using OutSystems.ObjectKeys;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Db;
using OutSystems.Internal.Db;
using System.Xml.Serialization;
using System.Collections;
using System.Collections.Generic;
using OutSystems.RuntimeCommon;

namespace ssCaseConferencing {

	public sealed partial class ENUserDocumentPermissionsEntity {
		public static string LocalViewName(int? tenant, string locale) {
			return ViewName(null, locale);
		}
		public static string ViewName(int? tenant, string locale) {
			return RsseSpaceCaseConferencingCore.ENUserDocumentPermissionsEntity.ViewName(tenant, locale);
		}
		public const int eSpaceId = RsseSpaceCaseConferencingCore.ENUserDocumentPermissionsEntity.eSpaceId;
	} // ENUserDocumentPermissionsEntity

	/// <summary>
	/// Entity <code>ENUserDocumentPermissionsEntityRecord</code> that represents the Service Studio entity
	///  <code>UserDocumentPermissions</code> <p> Description: </p>
	/// </summary>
	[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityRecordDetails("UserDocumentPermissions", "tgAiPEV3yE+UDDLl7Tdaaw", "U4Zx4qCUzUe0A+0C93K3BA", 0, "OSUSR_q0e_UserDocumentPermissions", "")]
	[Serializable()]
	public partial struct ENUserDocumentPermissionsEntityRecord: ISerializable, ITypedRecord<ENUserDocumentPermissionsEntityRecord>, ISimpleRecord {
		private static readonly GlobalObjectKey IdId = GlobalObjectKey.Parse("U4Zx4qCUzUe0A+0C93K3BA*y45NUODcmEawnZewKGW7Gw");
		private static readonly GlobalObjectKey IdDocumentId = GlobalObjectKey.Parse("U4Zx4qCUzUe0A+0C93K3BA*kVOsv0xY2E+jkyzRcYpQVw");
		private static readonly GlobalObjectKey IdUserId = GlobalObjectKey.Parse("U4Zx4qCUzUe0A+0C93K3BA*VPYZiZRJnE27BFUrquWyBg");

		public static void EnsureInitialized() {}
		[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("ID", 0, true, true, false)]
		[System.Xml.Serialization.XmlElement("Id")]
		private int _ssId;
		public int ssId {
			get {
				return _ssId;
			}
			set {
				if ((_ssId!=value) || OptimizedAttributes[0]) {
					ChangedAttributes = new BitArray(3, true);
					_ssId = value;
				}
			}
		}

		[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("DOCUMENTID", 0, false, false, true)]
		[System.Xml.Serialization.XmlElement("DocumentId")]
		private int _ssDocumentId;
		public int ssDocumentId {
			get {
				return _ssDocumentId;
			}
			set {
				if ((_ssDocumentId!=value) || OptimizedAttributes[1]) {
					ChangedAttributes[1] = true;
					_ssDocumentId = value;
				}
			}
		}

		[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("USERID", 0, false, false, true)]
		[System.Xml.Serialization.XmlElement("UserId")]
		private int _ssUserId;
		public int ssUserId {
			get {
				return _ssUserId;
			}
			set {
				if ((_ssUserId!=value) || OptimizedAttributes[2]) {
					ChangedAttributes[2] = true;
					_ssUserId = value;
				}
			}
		}


		public BitArray ChangedAttributes;

		public BitArray OptimizedAttributes;

		public ENUserDocumentPermissionsEntityRecord(params string[] dummy) {
			ChangedAttributes = new BitArray(3, true);
			OptimizedAttributes = new BitArray(3, false);
			_ssId = 0;
			_ssDocumentId = 0;
			_ssUserId = 0;
		}

		public BitArray[] GetDefaultOptimizedValues() {
			BitArray[] all = new BitArray[0];
			return all;
		}

		public BitArray[] AllOptimizedAttributes {
			set {
				if (value == null) {
				} else {
				}
			}
			get {
				BitArray[] all = new BitArray[0];
				return all;
			}
		}

		/// <summary>
		/// Read a record from database
		/// </summary>
		/// <param name="r"> Data base reader</param>
		/// <param name="index"> index</param>
		public void Read(IDataReader r, ref int index) {
			ssId = r.ReadInteger(index++, "UserDocumentPermissions.Id", 0);
			ssDocumentId = r.ReadEntityReference(index++, "UserDocumentPermissions.DocumentId", 0);
			ssUserId = r.ReadEntityReference(index++, "UserDocumentPermissions.UserId", 0);
			ChangedAttributes = new BitArray(3, false);
			OptimizedAttributes = new BitArray(3, false);
		}
		/// <summary>
		/// Read from database
		/// </summary>
		/// <param name="r"> Data reader</param>
		public void ReadDB(IDataReader r) {
			int index = 0;
			Read(r, ref index);
		}

		/// <summary>
		/// Read from record
		/// </summary>
		/// <param name="r"> Record</param>
		public void ReadIM(ENUserDocumentPermissionsEntityRecord r) {
			this = r;
		}


		public static bool operator == (ENUserDocumentPermissionsEntityRecord a, ENUserDocumentPermissionsEntityRecord b) {
			if (a.ssId != b.ssId) return false;
			if (a.ssDocumentId != b.ssDocumentId) return false;
			if (a.ssUserId != b.ssUserId) return false;
			return true;
		}

		public static bool operator != (ENUserDocumentPermissionsEntityRecord a, ENUserDocumentPermissionsEntityRecord b) {
			return !(a==b);
		}

		public override bool Equals(object o) {
			if (o.GetType() != typeof(ENUserDocumentPermissionsEntityRecord)) return false;
			return (this == (ENUserDocumentPermissionsEntityRecord) o);
		}

		public override int GetHashCode() {
			try {
				return base.GetHashCode()
				^ ssId.GetHashCode()
				^ ssDocumentId.GetHashCode()
				^ ssUserId.GetHashCode()
				;
			} catch {
				return base.GetHashCode();
			}
		}

		public void GetObjectData(SerializationInfo info, StreamingContext context) {
			Type objInfo = this.GetType();
			FieldInfo[] fields;
			fields = objInfo.GetFields(BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Public);
			for (int i = 0; i < fields.Length; i++)
			if (fields[i] .FieldType.IsSerializable)
			info.AddValue(fields[i] .Name, fields[i] .GetValue(this));
		}

		public ENUserDocumentPermissionsEntityRecord(SerializationInfo info, StreamingContext context) {
			ChangedAttributes = new BitArray(3, true);
			OptimizedAttributes = new BitArray(3, false);
			_ssId = 0;
			_ssDocumentId = 0;
			_ssUserId = 0;
			Type objInfo = this.GetType();
			FieldInfo[] fields;
			fields = objInfo.GetFields(BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Public);
			if (fields[0] .FieldType.IsSerializable)
			_ssId = (int) info.GetValue(fields[0] .Name, fields[0] .FieldType);
			if (fields[1] .FieldType.IsSerializable)
			_ssDocumentId = (int) info.GetValue(fields[1] .Name, fields[1] .FieldType);
			if (fields[2] .FieldType.IsSerializable)
			_ssUserId = (int) info.GetValue(fields[2] .Name, fields[2] .FieldType);
		}

		public void RecursiveReset() {
		}

		public void InternalRecursiveSave() {
		}


		public ENUserDocumentPermissionsEntityRecord Duplicate() {
			ENUserDocumentPermissionsEntityRecord t;
			t._ssId = this._ssId;
			t._ssDocumentId = this._ssDocumentId;
			t._ssUserId = this._ssUserId;
			t.ChangedAttributes = new BitArray(3);
			t.OptimizedAttributes = new BitArray(3);
			for (int i = 0; i < 3; i++) {
				t.ChangedAttributes[i] = ChangedAttributes[i];
				t.OptimizedAttributes[i] = OptimizedAttributes[i];
			}
			return t;
		}

		IRecord IRecord.Duplicate() {
			return Duplicate();
		}

		public void ToXml(Object parent, System.Xml.XmlElement baseElem, String fieldName, int detailLevel) {
			System.Xml.XmlElement recordElem = VarValue.AppendChild(baseElem, "Entity");
			if (fieldName != null) {
				VarValue.AppendAttribute(recordElem, "debug.field", fieldName);
				fieldName = fieldName.ToLowerInvariant();
			}
			if (detailLevel > 0) {
				if (!VarValue.FieldIsOptimized(parent, fieldName + ".Id")) VarValue.AppendAttribute(recordElem, "Id", ssId, detailLevel, TypeKind.Integer); else VarValue.AppendOptimizedAttribute(recordElem, "Id");
				if (!VarValue.FieldIsOptimized(parent, fieldName + ".DocumentId")) VarValue.AppendAttribute(recordElem, "DocumentId", ssDocumentId, detailLevel, TypeKind.EntityReference); else VarValue.AppendOptimizedAttribute(recordElem, "DocumentId");
				if (!VarValue.FieldIsOptimized(parent, fieldName + ".UserId")) VarValue.AppendAttribute(recordElem, "UserId", ssUserId, detailLevel, TypeKind.EntityReference); else VarValue.AppendOptimizedAttribute(recordElem, "UserId");
			} else {
				VarValue.AppendDeferredEvaluationElement(recordElem);
			}
		}

		public void EvaluateFields(VarValue variable, Object parent, String baseName, String fields) {
			String head = VarValue.GetHead(fields);
			String tail = VarValue.GetTail(fields);
			variable.Found = false;
			if (head == "id") {
				if (!VarValue.FieldIsOptimized(parent, baseName + ".Id")) variable.Value = ssId; else variable.Optimized = true;
			} else if (head == "documentid") {
				if (!VarValue.FieldIsOptimized(parent, baseName + ".DocumentId")) variable.Value = ssDocumentId; else variable.Optimized = true;
			} else if (head == "userid") {
				if (!VarValue.FieldIsOptimized(parent, baseName + ".UserId")) variable.Value = ssUserId; else variable.Optimized = true;
			}
			if (variable.Found && tail != null) variable.EvaluateFields(this, head, tail);
		}

		public bool ChangedAttributeGet(GlobalObjectKey key) {
			if (key.Equals(IdId)) {
				return ChangedAttributes[0];
			} else if (key.Equals(IdDocumentId)) {
				return ChangedAttributes[1];
			} else if (key.Equals(IdUserId)) {
				return ChangedAttributes[2];
			} else {
				throw new Exception("Invalid key");
			}
		}

		public bool OptimizedAttributeGet(GlobalObjectKey key) {
			if (key.Equals(IdId)) {
				return OptimizedAttributes[0];
			} else if (key.Equals(IdDocumentId)) {
				return OptimizedAttributes[1];
			} else if (key.Equals(IdUserId)) {
				return OptimizedAttributes[2];
			} else {
				throw new Exception("Invalid key");
			}
		}

		public object AttributeGet(GlobalObjectKey key) {
			if (key == IdId) {
				return ssId;
			} else if (key == IdDocumentId) {
				return ssDocumentId;
			} else if (key == IdUserId) {
				return ssUserId;
			} else {
				throw new Exception("Invalid key");
			}
		}
		public void FillFromOther(IRecord other) {
			ChangedAttributes = new BitArray(3);
			OptimizedAttributes = new BitArray(3);
			if (other == null) return;
			ssId = (int) other.AttributeGet(IdId);
			ChangedAttributes[0] = other.ChangedAttributeGet(IdId);
			OptimizedAttributes[0] = other.OptimizedAttributeGet(IdId);
			ssDocumentId = (int) other.AttributeGet(IdDocumentId);
			ChangedAttributes[1] = other.ChangedAttributeGet(IdDocumentId);
			OptimizedAttributes[1] = other.OptimizedAttributeGet(IdDocumentId);
			ssUserId = (int) other.AttributeGet(IdUserId);
			ChangedAttributes[2] = other.ChangedAttributeGet(IdUserId);
			OptimizedAttributes[2] = other.OptimizedAttributeGet(IdUserId);
		}
	} // ENUserDocumentPermissionsEntityRecord
	/// <summary>
	/// Structure <code>RCUserDocumentPermissionsRecord</code>
	/// </summary>
	[Serializable()]
	public partial struct RCUserDocumentPermissionsRecord: ISerializable, ITypedRecord<RCUserDocumentPermissionsRecord> {
		private static readonly GlobalObjectKey IdUserDocumentPermissions = GlobalObjectKey.Parse("2UmDmepsh0WSfJ_D1JexCA*4sVP2+admvI0qaL+tW6tTg");

		public static void EnsureInitialized() {}
		[System.Xml.Serialization.XmlElement("UserDocumentPermissions")]
		public ENUserDocumentPermissionsEntityRecord ssENUserDocumentPermissions;


		public static implicit operator ENUserDocumentPermissionsEntityRecord(RCUserDocumentPermissionsRecord r) {
			return r.ssENUserDocumentPermissions;
		}

		public static implicit operator RCUserDocumentPermissionsRecord(ENUserDocumentPermissionsEntityRecord r) {
			RCUserDocumentPermissionsRecord res = new RCUserDocumentPermissionsRecord(null);
			res.ssENUserDocumentPermissions = r;
			return res;
		}

		public BitArray ChangedAttributes {
			set {
				ssENUserDocumentPermissions.ChangedAttributes = value;
			}
			get {
				return ssENUserDocumentPermissions.ChangedAttributes;
			}
		}
		public BitArray OptimizedAttributes;

		public RCUserDocumentPermissionsRecord(params string[] dummy) {
			OptimizedAttributes = null;
			ssENUserDocumentPermissions = new ENUserDocumentPermissionsEntityRecord(null);
		}

		public BitArray[] GetDefaultOptimizedValues() {
			BitArray[] all = new BitArray[1];
			all[0] = new BitArray(3, false);
			return all;
		}

		public BitArray[] AllOptimizedAttributes {
			set {
				if (value == null) {
					ssENUserDocumentPermissions.OptimizedAttributes = GetDefaultOptimizedValues()[0];
				} else {
					ssENUserDocumentPermissions.OptimizedAttributes = value[0];
				}
			}
			get {
				BitArray[] all = new BitArray[1];
				all[0] = ssENUserDocumentPermissions.OptimizedAttributes;
				return all;
			}
		}

		/// <summary>
		/// Read a record from database
		/// </summary>
		/// <param name="r"> Data base reader</param>
		/// <param name="index"> index</param>
		public void Read(IDataReader r, ref int index) {
			ssENUserDocumentPermissions.Read(r, ref index);
		}
		/// <summary>
		/// Read from database
		/// </summary>
		/// <param name="r"> Data reader</param>
		public void ReadDB(IDataReader r) {
			int index = 0;
			Read(r, ref index);
		}

		/// <summary>
		/// Read from record
		/// </summary>
		/// <param name="r"> Record</param>
		public void ReadIM(RCUserDocumentPermissionsRecord r) {
			this = r;
		}


		public static bool operator == (RCUserDocumentPermissionsRecord a, RCUserDocumentPermissionsRecord b) {
			if (a.ssENUserDocumentPermissions != b.ssENUserDocumentPermissions) return false;
			return true;
		}

		public static bool operator != (RCUserDocumentPermissionsRecord a, RCUserDocumentPermissionsRecord b) {
			return !(a==b);
		}

		public override bool Equals(object o) {
			if (o.GetType() != typeof(RCUserDocumentPermissionsRecord)) return false;
			return (this == (RCUserDocumentPermissionsRecord) o);
		}

		public override int GetHashCode() {
			try {
				return base.GetHashCode()
				^ ssENUserDocumentPermissions.GetHashCode()
				;
			} catch {
				return base.GetHashCode();
			}
		}

		public void GetObjectData(SerializationInfo info, StreamingContext context) {
			Type objInfo = this.GetType();
			FieldInfo[] fields;
			fields = objInfo.GetFields(BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Public);
			for (int i = 0; i < fields.Length; i++)
			if (fields[i] .FieldType.IsSerializable)
			info.AddValue(fields[i] .Name, fields[i] .GetValue(this));
		}

		public RCUserDocumentPermissionsRecord(SerializationInfo info, StreamingContext context) {
			OptimizedAttributes = null;
			ssENUserDocumentPermissions = new ENUserDocumentPermissionsEntityRecord(null);
			Type objInfo = this.GetType();
			FieldInfo[] fields;
			fields = objInfo.GetFields(BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Public);
			if (fields[0] .FieldType.IsSerializable)
			ssENUserDocumentPermissions = (ENUserDocumentPermissionsEntityRecord) info.GetValue(fields[0] .Name, fields[0] .FieldType);
		}

		public void RecursiveReset() {
			ssENUserDocumentPermissions.RecursiveReset();
		}

		public void InternalRecursiveSave() {
			ssENUserDocumentPermissions.InternalRecursiveSave();
		}


		public RCUserDocumentPermissionsRecord Duplicate() {
			RCUserDocumentPermissionsRecord t;
			t.ssENUserDocumentPermissions = (ENUserDocumentPermissionsEntityRecord) this.ssENUserDocumentPermissions.Duplicate();
			t.OptimizedAttributes = null;
			return t;
		}

		IRecord IRecord.Duplicate() {
			return Duplicate();
		}

		public void ToXml(Object parent, System.Xml.XmlElement baseElem, String fieldName, int detailLevel) {
			System.Xml.XmlElement recordElem = VarValue.AppendChild(baseElem, "Record");
			if (fieldName != null) {
				VarValue.AppendAttribute(recordElem, "debug.field", fieldName);
			}
			if (detailLevel > 0) {
				ssENUserDocumentPermissions.ToXml(this, recordElem, "UserDocumentPermissions", detailLevel - 1);
			} else {
				VarValue.AppendDeferredEvaluationElement(recordElem);
			}
		}

		public void EvaluateFields(VarValue variable, Object parent, String baseName, String fields) {
			String head = VarValue.GetHead(fields);
			String tail = VarValue.GetTail(fields);
			variable.Found = false;
			if (head == "userdocumentpermissions") {
				if (!VarValue.FieldIsOptimized(parent, baseName + ".UserDocumentPermissions")) variable.Value = ssENUserDocumentPermissions; else variable.Optimized = true;
				variable.SetFieldName("userdocumentpermissions");
			}
			if (variable.Found && tail != null) variable.EvaluateFields(this, head, tail);
		}

		public bool ChangedAttributeGet(GlobalObjectKey key) {
			return ssENUserDocumentPermissions.ChangedAttributeGet(key);
		}

		public bool OptimizedAttributeGet(GlobalObjectKey key) {
			return ssENUserDocumentPermissions.OptimizedAttributeGet(key);
		}

		public object AttributeGet(GlobalObjectKey key) {
			if (key == IdUserDocumentPermissions) {
				return ssENUserDocumentPermissions;
			} else {
				throw new Exception("Invalid key");
			}
		}
		public void FillFromOther(IRecord other) {
			if (other == null) return;
			ssENUserDocumentPermissions.FillFromOther((IRecord) other.AttributeGet(IdUserDocumentPermissions));
		}
	} // RCUserDocumentPermissionsRecord
	/// <summary>
	/// RecordList type <code>RLUserDocumentPermissionsRecordList</code> that represents a record list of
	///  <code>UserDocumentPermissions</code>
	/// </summary>
	[Serializable()]
	public partial class RLUserDocumentPermissionsRecordList: GenericRecordList<RCUserDocumentPermissionsRecord>, IEnumerable, IEnumerator, ISerializable {
		public static void EnsureInitialized() {}

		protected override RCUserDocumentPermissionsRecord GetElementDefaultValue() {
			return new RCUserDocumentPermissionsRecord("");
		}

		public T[] ToArray<T>(Func<RCUserDocumentPermissionsRecord, T> converter) {
			return ToArray(this, converter);
		}

		public static T[] ToArray<T>(RLUserDocumentPermissionsRecordList recordlist, Func<RCUserDocumentPermissionsRecord, T> converter) {
			T[] result = new T[recordlist.Length];
			recordlist.StartIteration();
			while (!recordlist.Eof) {
				result[recordlist.CurrentRowNumber] = converter(recordlist.CurrentRec);
				recordlist.Advance();
			}
			recordlist.EndIteration();
			return result;
		}

		public static RLUserDocumentPermissionsRecordList ToList<T>(T[] array, Func <T, RCUserDocumentPermissionsRecord> converter) {
			RLUserDocumentPermissionsRecordList result = new RLUserDocumentPermissionsRecordList();
			if (array != null) {
				foreach(T item in array) {
					result.Append(converter(item));
				}
			}
			return result;
		}
		/// <summary>
		/// Default Constructor
		/// </summary>
		public RLUserDocumentPermissionsRecordList(): base() {
		}

		/// <summary>
		/// Constructor with transaction parameter
		/// </summary>
		/// <param name="trans"> IDbTransaction Parameter</param>
		[Obsolete("Use the Default Constructor and set the Transaction afterwards.")]
		public RLUserDocumentPermissionsRecordList(IDbTransaction trans): base(trans) {
		}

		/// <summary>
		/// Constructor with transaction parameter and alternate read method
		/// </summary>
		/// <param name="trans"> IDbTransaction Parameter</param>
		/// <param name="alternateReadDBMethod"> Alternate Read Method</param>
		[Obsolete("Use the Default Constructor and set the Transaction afterwards.")]
		public RLUserDocumentPermissionsRecordList(IDbTransaction trans, ReadDBMethodDelegate alternateReadDBMethod): this(trans) {
			this.alternateReadDBMethod = alternateReadDBMethod;
		}

		/// <summary>
		/// Constructor declaration for serialization
		/// </summary>
		/// <param name="info"> SerializationInfo</param>
		/// <param name="context"> StreamingContext</param>
		public RLUserDocumentPermissionsRecordList(SerializationInfo info, StreamingContext context): base(info, context) {
		}

		public override BitArray[] GetDefaultOptimizedValues() {
			BitArray[] def = new BitArray[1];
			def[0] = new BitArray(3, false);
			return def;
		}
		/// <summary>
		/// Create as new list
		/// </summary>
		/// <returns>The new record list</returns>
		protected override OSList<RCUserDocumentPermissionsRecord> NewList() {
			return new RLUserDocumentPermissionsRecordList();
		}


	} // RLUserDocumentPermissionsRecordList

	/// <summary>
	/// RecordList type <code>RLUserDocumentPermissionsList</code> that represents a record list of
	///  <code>UserIdentifier, Integer, DocumentsIdentifier</code>
	/// </summary>
	[Serializable()]
	public partial class RLUserDocumentPermissionsList: GenericRecordList<ENUserDocumentPermissionsEntityRecord>, IEnumerable, IEnumerator, ISerializable {
		public static void EnsureInitialized() {}

		protected override ENUserDocumentPermissionsEntityRecord GetElementDefaultValue() {
			return new ENUserDocumentPermissionsEntityRecord("");
		}

		public T[] ToArray<T>(Func<ENUserDocumentPermissionsEntityRecord, T> converter) {
			return ToArray(this, converter);
		}

		public static T[] ToArray<T>(RLUserDocumentPermissionsList recordlist, Func<ENUserDocumentPermissionsEntityRecord, T> converter) {
			T[] result = new T[recordlist.Length];
			recordlist.StartIteration();
			while (!recordlist.Eof) {
				result[recordlist.CurrentRowNumber] = converter(recordlist.CurrentRec);
				recordlist.Advance();
			}
			recordlist.EndIteration();
			return result;
		}

		public static RLUserDocumentPermissionsList ToList<T>(T[] array, Func <T, ENUserDocumentPermissionsEntityRecord> converter) {
			RLUserDocumentPermissionsList result = new RLUserDocumentPermissionsList();
			if (array != null) {
				foreach(T item in array) {
					result.Append(converter(item));
				}
			}
			return result;
		}
		/// <summary>
		/// Default Constructor
		/// </summary>
		public RLUserDocumentPermissionsList(): base() {
		}

		/// <summary>
		/// Constructor with transaction parameter
		/// </summary>
		/// <param name="trans"> IDbTransaction Parameter</param>
		[Obsolete("Use the Default Constructor and set the Transaction afterwards.")]
		public RLUserDocumentPermissionsList(IDbTransaction trans): base(trans) {
		}

		/// <summary>
		/// Constructor with transaction parameter and alternate read method
		/// </summary>
		/// <param name="trans"> IDbTransaction Parameter</param>
		/// <param name="alternateReadDBMethod"> Alternate Read Method</param>
		[Obsolete("Use the Default Constructor and set the Transaction afterwards.")]
		public RLUserDocumentPermissionsList(IDbTransaction trans, ReadDBMethodDelegate alternateReadDBMethod): this(trans) {
			this.alternateReadDBMethod = alternateReadDBMethod;
		}

		/// <summary>
		/// Constructor declaration for serialization
		/// </summary>
		/// <param name="info"> SerializationInfo</param>
		/// <param name="context"> StreamingContext</param>
		public RLUserDocumentPermissionsList(SerializationInfo info, StreamingContext context): base(info, context) {
		}

		public override BitArray[] GetDefaultOptimizedValues() {
			BitArray[] def = new BitArray[0];
			return def;
		}
		/// <summary>
		/// Create as new list
		/// </summary>
		/// <returns>The new record list</returns>
		protected override OSList<ENUserDocumentPermissionsEntityRecord> NewList() {
			return new RLUserDocumentPermissionsList();
		}


	} // RLUserDocumentPermissionsList
	public partial class ExtendedActions {
		/// <summary>
		/// Action: CreateUserDocumentPermissions
		/// </summary>

		public static void CreateUserDocumentPermissions(HeContext heContext, RCUserDocumentPermissionsRecord inParamSource, out int outParamId) {
			outParamId = 0;

			int oldCurrentESpaceId = heContext.CurrentESpaceId;
			try {
				heContext.CurrentESpaceId = ENUserDocumentPermissionsEntity.eSpaceId;
				ENUserDocumentPermissionsEntityRecord ssENUserDocumentPermissions = inParamSource;
				using(Transaction trans = DatabaseAccess.ForCurrentDatabase.GetRequestTransaction()) {
					string insertSql =
					 "SET NOCOUNT ON; INSERT INTO " + ENUserDocumentPermissionsEntity.LocalViewName(null, null) + " (" +
					 " [DOCUMENTID]" +
					 ", [USERID]" +
					 " ) VALUES (" +
					 " @ssDocumentId" +
					 ", @ssUserId" +
					 " ) ; SELECT SCOPE_IDENTITY();";
					Command insertSqlCmd = trans.CreateCommand(insertSql);
					if ((ssENUserDocumentPermissions.ssDocumentId==0)) {
						insertSqlCmd.CreateParameter("@ssDocumentId", DBNull.Value);
					} else {
						insertSqlCmd.CreateParameter("@ssDocumentId", DbType.Int32, ssENUserDocumentPermissions.ssDocumentId);
					}
					if ((ssENUserDocumentPermissions.ssUserId==0)) {
						insertSqlCmd.CreateParameter("@ssUserId", DBNull.Value);
					} else {
						insertSqlCmd.CreateParameter("@ssUserId", DbType.Int32, ssENUserDocumentPermissions.ssUserId);
					}
					outParamId = (int) Convert.ChangeType(insertSqlCmd.ExecuteScalar("Entity Action CreateUserDocumentPermissions", true), typeof(int));
				}
			} finally {
				heContext.CurrentESpaceId = oldCurrentESpaceId;
			}
		}

		/// <summary>
		/// Action: CreateOrUpdateUserDocumentPermissions
		/// </summary>

		public static void CreateOrUpdateUserDocumentPermissions(HeContext heContext, BitArray usedFields, RCUserDocumentPermissionsRecord inParamSource, out int outParamId) {
			outParamId = 0;

			int oldCurrentESpaceId = heContext.CurrentESpaceId;
			try {
				heContext.CurrentESpaceId = ENUserDocumentPermissionsEntity.eSpaceId;
				ENUserDocumentPermissionsEntityRecord ssENUserDocumentPermissions = inParamSource;
				using(Transaction trans = DatabaseAccess.ForCurrentDatabase.GetRequestTransaction()) {
					if (usedFields == null) {
						usedFields = new BitArray(3, true);
					}
					string updateSet = "SET NOCOUNT OFF; UPDATE " + ENUserDocumentPermissionsEntity.LocalViewName(heContext.AppInfo.Tenant.Id, BuiltInFunction.GetCurrentLocale()) + " SET ";
					string parameters = "";
					parameters = (usedFields[1] ?(StringUtils.SuffixIfNotEmpty(parameters, ", ") + "[DOCUMENTID] = @ssDocumentId"): parameters);
					parameters = (usedFields[2] ?(StringUtils.SuffixIfNotEmpty(parameters, ", ") + "[USERID] = @ssUserId"): parameters);
					string whereCondition = " WHERE [ID] = @ssENUserDocumentPermissionsssId";
					string sql = updateSet + parameters + whereCondition;
					Command sqlCmd = trans.CreateCommand(sql);
					int counter = 0;
					if (usedFields[1]) {
						if ((ssENUserDocumentPermissions.ssDocumentId==0)) {
							sqlCmd.CreateParameter("@ssDocumentId", DBNull.Value);
						} else {
							sqlCmd.CreateParameter("@ssDocumentId", DbType.Int32, ssENUserDocumentPermissions.ssDocumentId);
						}
						counter++;
					}
					if (usedFields[2]) {
						if ((ssENUserDocumentPermissions.ssUserId==0)) {
							sqlCmd.CreateParameter("@ssUserId", DBNull.Value);
						} else {
							sqlCmd.CreateParameter("@ssUserId", DbType.Int32, ssENUserDocumentPermissions.ssUserId);
						}
						counter++;
					}
					if (counter == 0) {
						string dummyUpdate = "[DOCUMENTID] = [DOCUMENTID]";
						string noUpdate = updateSet + dummyUpdate + whereCondition;
						sqlCmd = trans.CreateCommand(noUpdate);
					}
					sqlCmd.CreateParameter("@ssENUserDocumentPermissionsssId", DbType.Int32, ssENUserDocumentPermissions.ssId);
					counter = sqlCmd.ExecuteNonQueryWithoutTransformParametersSyntax("Entity Action CreateOrUpdateUserDocumentPermissions (update)", true);
					if (counter == 0) {
						string insertSql =
						 "SET NOCOUNT ON; INSERT INTO " + ENUserDocumentPermissionsEntity.LocalViewName(null, null) + " (" +
						 " [DOCUMENTID]" +
						 ", [USERID]" +
						 " ) VALUES (" +
						 " @ssDocumentId" +
						 ", @ssUserId" +
						 " ) ; SELECT SCOPE_IDENTITY();";
						Command insertSqlCmd = trans.CreateCommand(insertSql);
						if ((ssENUserDocumentPermissions.ssDocumentId==0)) {
							insertSqlCmd.CreateParameter("@ssDocumentId", DBNull.Value);
						} else {
							insertSqlCmd.CreateParameter("@ssDocumentId", DbType.Int32, ssENUserDocumentPermissions.ssDocumentId);
						}
						if ((ssENUserDocumentPermissions.ssUserId==0)) {
							insertSqlCmd.CreateParameter("@ssUserId", DBNull.Value);
						} else {
							insertSqlCmd.CreateParameter("@ssUserId", DbType.Int32, ssENUserDocumentPermissions.ssUserId);
						}
						outParamId = (int) Convert.ChangeType(insertSqlCmd.ExecuteScalar("Entity Action CreateOrUpdateUserDocumentPermissions", true), typeof(int));
					} else {
						outParamId = ssENUserDocumentPermissions.ssId;
					}
				}
			} finally {
				heContext.CurrentESpaceId = oldCurrentESpaceId;
			}
		}

		/// <summary>
		/// Action: DeleteUserDocumentPermissions
		/// </summary>

		public static void DeleteUserDocumentPermissions(HeContext heContext, int inParamId) {
			int oldCurrentESpaceId = heContext.CurrentESpaceId;
			try {
				heContext.CurrentESpaceId = ENUserDocumentPermissionsEntity.eSpaceId;
				using(Transaction trans = DatabaseAccess.ForCurrentDatabase.GetRequestTransaction()) {
					string sql =
					 "DELETE " +
					 "FROM " + ENUserDocumentPermissionsEntity.LocalViewName(heContext.AppInfo.Tenant.Id, BuiltInFunction.GetCurrentLocale()) + " " +
					 "WHERE [ID] = @inParamId";
					Command sqlCmd = trans.CreateCommand(sql);
					sqlCmd.CreateParameter("@inParamId", DbType.Int32, inParamId);
					sqlCmd.ExecuteNonQueryWithoutTransformParametersSyntax("Entity Action DeleteUserDocumentPermissions", true);
				}
			} finally {
				heContext.CurrentESpaceId = oldCurrentESpaceId;
			}
		}

		/// <summary>
		/// Action: GetUserDocumentPermissions
		/// </summary>

		public static void GetUserDocumentPermissions(HeContext heContext, int inParamId, out RCUserDocumentPermissionsRecord outParamRecord) {
			outParamRecord = new RCUserDocumentPermissionsRecord(null);

			int oldCurrentESpaceId = heContext.CurrentESpaceId;
			try {
				heContext.CurrentESpaceId = ENUserDocumentPermissionsEntity.eSpaceId;
				using(Transaction trans = DatabaseAccess.ForCurrentDatabase.GetRequestTransaction()) {
					string sql =
					 "SELECT " +
					 " [ID]" +
					 ", [DOCUMENTID]" +
					 ", [USERID]" +
					 " FROM " + ENUserDocumentPermissionsEntity.LocalViewName(heContext.AppInfo.Tenant.Id, BuiltInFunction.GetCurrentLocale()) + " " +
					 "WHERE [ID] = @inParamId";
					Command sqlCmd = trans.CreateCommand(sql);
					sqlCmd.CreateParameter("@inParamId", DbType.Int32, inParamId);
					using(IDataReader reader = sqlCmd.ExecuteReader("Entity Action GetUserDocumentPermissions", true, false, false)) {
						if (reader.Read()) {
							outParamRecord.ReadDB(reader);
							outParamRecord.AllOptimizedAttributes = new BitArray[] {
								new BitArray(3, false)
							}
							;
						} else
						throw new DataBaseException(ENUserDocumentPermissionsEntity.LocalViewName(heContext.AppInfo.Tenant.Id, BuiltInFunction.GetCurrentLocale()) + " with key " + inParamId + " was not found");
					}
				}
			} finally {
				heContext.CurrentESpaceId = oldCurrentESpaceId;
			}
		}

		/// <summary>
		/// Action: GetUserDocumentPermissionsForUpdate
		/// </summary>

		public static void GetUserDocumentPermissionsForUpdate(HeContext heContext, int inParamId, out RCUserDocumentPermissionsRecord outParamRecord) {
			outParamRecord = new RCUserDocumentPermissionsRecord(null);

			int oldCurrentESpaceId = heContext.CurrentESpaceId;
			try {
				heContext.CurrentESpaceId = ENUserDocumentPermissionsEntity.eSpaceId;
				using(Transaction trans = DatabaseAccess.ForCurrentDatabase.GetRequestTransaction()) {
					string sql =
					 "SELECT " +
					 " [ID]" +
					 ", [DOCUMENTID]" +
					 ", [USERID]" +
					 "FROM " + ENUserDocumentPermissionsEntity.LocalViewName(heContext.AppInfo.Tenant.Id, BuiltInFunction.GetCurrentLocale()) + " WITH ( UPDLOCK ) " +
					 "WHERE [ID] = @inParamId ";
					Command sqlCmd = trans.CreateCommand(sql);
					sqlCmd.CreateParameter("@inParamId", DbType.Int32, inParamId);
					using(IDataReader reader = sqlCmd.ExecuteReader("Entity Action GetUserDocumentPermissionsForUpdate", true, false, false)) {
						if (reader.Read()) {
							outParamRecord.ReadDB(reader);
							outParamRecord.AllOptimizedAttributes = new BitArray[] {
								new BitArray(3, false)
							}
							;
						} else
						throw new DataBaseException(ENUserDocumentPermissionsEntity.LocalViewName(heContext.AppInfo.Tenant.Id, BuiltInFunction.GetCurrentLocale()) + " with key " + inParamId + " was not found");
					}
				}
			} finally {
				heContext.CurrentESpaceId = oldCurrentESpaceId;
			}
		}

		/// <summary>
		/// Action: UpdateUserDocumentPermissions
		/// </summary>

		public static void UpdateUserDocumentPermissions(HeContext heContext, BitArray usedFields, RCUserDocumentPermissionsRecord inParamSource) {
			int oldCurrentESpaceId = heContext.CurrentESpaceId;
			try {
				heContext.CurrentESpaceId = ENUserDocumentPermissionsEntity.eSpaceId;
				ENUserDocumentPermissionsEntityRecord ssENUserDocumentPermissions = inParamSource;
				using(Transaction trans = DatabaseAccess.ForCurrentDatabase.GetRequestTransaction()) {
					if (usedFields == null) {
						usedFields = new BitArray(3, true);
					}
					string updateSet = "SET NOCOUNT OFF; UPDATE " + ENUserDocumentPermissionsEntity.LocalViewName(heContext.AppInfo.Tenant.Id, BuiltInFunction.GetCurrentLocale()) + " SET ";
					string parameters = "";
					parameters = (usedFields[1] ?(StringUtils.SuffixIfNotEmpty(parameters, ", ") + "[DOCUMENTID] = @ssDocumentId"): parameters);
					parameters = (usedFields[2] ?(StringUtils.SuffixIfNotEmpty(parameters, ", ") + "[USERID] = @ssUserId"): parameters);
					string whereCondition = " WHERE [ID] = @ssENUserDocumentPermissionsssId";
					string sql = updateSet + parameters + whereCondition;
					Command sqlCmd = trans.CreateCommand(sql);
					int counter = 0;
					if (usedFields[1]) {
						if ((ssENUserDocumentPermissions.ssDocumentId==0)) {
							sqlCmd.CreateParameter("@ssDocumentId", DBNull.Value);
						} else {
							sqlCmd.CreateParameter("@ssDocumentId", DbType.Int32, ssENUserDocumentPermissions.ssDocumentId);
						}
						counter++;
					}
					if (usedFields[2]) {
						if ((ssENUserDocumentPermissions.ssUserId==0)) {
							sqlCmd.CreateParameter("@ssUserId", DBNull.Value);
						} else {
							sqlCmd.CreateParameter("@ssUserId", DbType.Int32, ssENUserDocumentPermissions.ssUserId);
						}
						counter++;
					}
					if (counter == 0) {
						string dummyUpdate = "[DOCUMENTID] = [DOCUMENTID]";
						string noUpdate = updateSet + dummyUpdate + whereCondition;
						sqlCmd = trans.CreateCommand(noUpdate);
					}
					sqlCmd.CreateParameter("@ssENUserDocumentPermissionsssId", DbType.Int32, ssENUserDocumentPermissions.ssId);
					if (sqlCmd.ExecuteNonQueryWithoutTransformParametersSyntax("Entity Action UpdateUserDocumentPermissions", true) <= 0)
					throw new DataBaseException(ENUserDocumentPermissionsEntity.LocalViewName(heContext.AppInfo.Tenant.Id, BuiltInFunction.GetCurrentLocale()) + " with key " + ssENUserDocumentPermissions.ssId + " was not updated");
				}
			} finally {
				heContext.CurrentESpaceId = oldCurrentESpaceId;
			}
		}

	}
}

namespace ssCaseConferencing {
	[XmlType("UserDocumentPermissions")]
	public class WORCUserDocumentPermissionsRecord {
		[System.Xml.Serialization.XmlElement("Id")]
		public int varWSId;

		[System.Xml.Serialization.XmlElement("DocumentId")]
		public int varWSDocumentId;

		[System.Xml.Serialization.XmlElement("UserId")]
		public int varWSUserId;

		public WORCUserDocumentPermissionsRecord() {
			varWSId = (int) 0;
			varWSDocumentId = (int) 0;
			varWSUserId = (int) 0;
		}

		public WORCUserDocumentPermissionsRecord(ENUserDocumentPermissionsEntityRecord r) {
			varWSId = (int) r.ssId;
			varWSDocumentId = (int) r.ssDocumentId;
			varWSUserId = (int) r.ssUserId;
		}

		public static RLUserDocumentPermissionsList ToRecordList(WORCUserDocumentPermissionsRecord[] array) {
			RLUserDocumentPermissionsList rl = new RLUserDocumentPermissionsList();
			if (array != null) {
				foreach(WORCUserDocumentPermissionsRecord val in array) {
					rl.Append(val);
				}
			}
			return rl;
		}

		public static WORCUserDocumentPermissionsRecord[] FromRecordList(RLUserDocumentPermissionsList rl) {
			WORCUserDocumentPermissionsRecord[] array = new WORCUserDocumentPermissionsRecord[rl == null ? 0: rl.Length];
			for (int i = 0; i < array.Length; i++) {
				array[i] = rl.Data[i];
			}
			return array;
		}
	}
}

namespace ssCaseConferencing {
	partial struct RCUserDocumentPermissionsRecord {
		public static implicit operator WORCUserDocumentPermissionsRecord(RCUserDocumentPermissionsRecord r) {
			return new WORCUserDocumentPermissionsRecord(r.ssENUserDocumentPermissions);
		}

		public static implicit operator RCUserDocumentPermissionsRecord(WORCUserDocumentPermissionsRecord w) {
			RCUserDocumentPermissionsRecord r = new RCUserDocumentPermissionsRecord("");
			if (w != null) {
				r.ssENUserDocumentPermissions = w;
			}
			return r;
		}

	}

	partial struct ENUserDocumentPermissionsEntityRecord {
		public static implicit operator WORCUserDocumentPermissionsRecord(ENUserDocumentPermissionsEntityRecord r) {
			return new WORCUserDocumentPermissionsRecord(r);
		}

		public static implicit operator ENUserDocumentPermissionsEntityRecord(WORCUserDocumentPermissionsRecord w) {
			ENUserDocumentPermissionsEntityRecord r = new ENUserDocumentPermissionsEntityRecord("");
			if (w != null) {
				r.ssId = (int) w.varWSId;
				r.ssDocumentId = (int) w.varWSDocumentId;
				r.ssUserId = (int) w.varWSUserId;
			}
			return r;
		}

	}
}


namespace ssCaseConferencing {
	[Serializable()]
	public partial class WORLUserDocumentPermissionsRecordList {
		public WORCUserDocumentPermissionsRecord[] Array;


		public WORLUserDocumentPermissionsRecordList(WORCUserDocumentPermissionsRecord[] r) {
			if (r == null)
			Array = new WORCUserDocumentPermissionsRecord[0];
			else
			Array = r;
		}
		public WORLUserDocumentPermissionsRecordList() {
			Array = new WORCUserDocumentPermissionsRecord[0];
		}

		public WORLUserDocumentPermissionsRecordList(RLUserDocumentPermissionsRecordList rl) {
			rl=(RLUserDocumentPermissionsRecordList) rl.Duplicate();
			Array = new WORCUserDocumentPermissionsRecord[rl.Length];
			while (!rl.Eof) {
				Array[rl.CurrentRowNumber] = new WORCUserDocumentPermissionsRecord(rl.CurrentRec);
				rl.Advance();
			}
		}

	}
}

namespace ssCaseConferencing {
	partial class RLUserDocumentPermissionsRecordList {
		public static implicit operator RLUserDocumentPermissionsRecordList(WORCUserDocumentPermissionsRecord[] array) {
			RLUserDocumentPermissionsRecordList rl = new RLUserDocumentPermissionsRecordList();
			if (array != null) {
				foreach(WORCUserDocumentPermissionsRecord val in array) {
					rl.Append((RCUserDocumentPermissionsRecord) val);
				}
			}
			return rl;
		}
		public static implicit operator WORCUserDocumentPermissionsRecord[](RLUserDocumentPermissionsRecordList rl) {
			WORCUserDocumentPermissionsRecord[] array = new WORCUserDocumentPermissionsRecord[rl == null ? 0: rl.Length];
			for (int i = 0; i < array.Length; i++) {
				array[i] = (RCUserDocumentPermissionsRecord) rl.Data[i];
			}
			return array;
		}
	}
}

namespace ssCaseConferencing {
	partial class WORLUserDocumentPermissionsRecordList {
		public static implicit operator RLUserDocumentPermissionsRecordList(WORLUserDocumentPermissionsRecordList w) {
			return w.Array;
		}
		public static implicit operator WORLUserDocumentPermissionsRecordList(RLUserDocumentPermissionsRecordList rl) {
			return new WORLUserDocumentPermissionsRecordList(rl);
		}
		public static implicit operator WORCUserDocumentPermissionsRecord[](WORLUserDocumentPermissionsRecordList w) {
			if (w != null) {
				return w.Array;
			}
			return null;
		}
		public static implicit operator WORLUserDocumentPermissionsRecordList(WORCUserDocumentPermissionsRecord[] array) {
			return new WORLUserDocumentPermissionsRecordList(array);
		}
	}
}

